# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-node-versions:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x, 20.x, 21.x]
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: streetsidesoftware/actions/public/setup-node-pnpm@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install - Build - Test
        uses: ./.github/actions/install-build-test

  test-os:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x]
        os:
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: streetsidesoftware/actions/public/setup-node-pnpm@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install - Build - Test
        uses: ./.github/actions/install-build-test

  coverage:
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x]
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run coverage

      - name: Upload coverage Coveralls
        uses: coverallsapp/github-action@1134c89e4bf10443bf8f0ec69640b667cfd91041 # 2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v3
